// Code generated by protoc-gen-go.
// source: login.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 玩家登陆
type GamerLoginC2S struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Channel          *string `protobuf:"bytes,3,opt,name=channel" json:"channel,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GamerLoginC2S) Reset()                    { *m = GamerLoginC2S{} }
func (m *GamerLoginC2S) String() string            { return proto.CompactTextString(m) }
func (*GamerLoginC2S) ProtoMessage()               {}
func (*GamerLoginC2S) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *GamerLoginC2S) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GamerLoginC2S) GetChannel() string {
	if m != nil && m.Channel != nil {
		return *m.Channel
	}
	return ""
}

func init() {
	proto.RegisterType((*GamerLoginC2S)(nil), "GamerLoginC2S")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe1, 0xe2, 0x75, 0x4f, 0xcc, 0x4d, 0x2d,
	0xf2, 0x01, 0x89, 0x39, 0x1b, 0x05, 0x0b, 0x71, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x0a, 0xf1, 0x73, 0xb1, 0x27, 0x67, 0x24, 0xe6, 0xe5, 0xa5, 0xe6, 0x48, 0x30, 0x2b,
	0x30, 0x6a, 0x70, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff, 0x73, 0x3a, 0xb7, 0xc4, 0x3b, 0x00, 0x00,
	0x00,
}
